version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://host.docker.internal:8000
    depends_on:
      - backend
    networks:
      - app-network

  unit_tests:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    environment:
      - PYTHONPATH=/app
    command: ["pytest", "/app/unit_tests.py"]
    networks:
      - app-network

  integration_test:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: ["pytest", "integration_test.py"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
